theme: jekyll-theme-cayman
title: Image Quality Assessment in the Modern Age
description: This tutorial provides the audience with the basic theories, methodologies, 
and current progresses of image quality assessment (IQA). From an actionable perspective, 
we will first revisit several subjective quality assessment methodologies, 
with emphasis on how to properly select visual stimuli. We will then present 
in detail the design principles of objective quality assessment models, 
supplemented by an in-depth analysis of their advantages and disadvantages. 
Both hand-engineered and (deep) learning-based methods will be covered. 
Moreover, the limitations with the conventional model comparison methodology for objective quality models will be pointed out, 
and novel comparison methodologies such as those based on the theory of "analysis by synthesis" will be introduced. 
We will last discuss the real-world multimedia applications of IQA, and give a list of open challenging problems, 
in the hope of encouraging more and more talented researchers and engineers devoting to this exciting and rewarding research field.
