theme: jekyll-theme-cayman
title: Image Quality Assessment in the Modern Age
description: [Kede Ma](https://kedema.org/), [Yuming Fang](http://sim.jxufe.cn/JDMKL/ymfang_EN.html)"
show_downloads: false
